### PR TITLE
Add TPEI Instruction and associated Facility

### PR DESCRIPTION
**Pull request by dominik-steenken**
This PR adds the `TPEI` system instruction, as well as its associated facility `Test Pending External Instruction`. The facility is defined as being available from `Arch12`/`z14`/`zMidas` forward. The PR also adds tests for the assembler and disassembler. `TPEI` does not participate in code generation.

### CODE REVIEW

**Comment by dominik-steenken** [comment]
@JonPsson1 @uweigand I have a handful of questions about the contents of this PR that i would appreciate some feedback for..
1. This PR assumes it is corrcect to use the same scheduling info for `TPEI` as for `TPI`. Is this correct?  Where could i find information for potential dependencies of this instruction, and how would i map that to the template parameters available for `InstRW`?
2. I picked `InherentDualRRE` as the instruction format, and set `hasSideEffects` to `0` based on the description in the POP. Is this correct?
3. The POP contains a section that describes a vector indicating which facilities are available, and the specific bit defined for `Test Pending External Interruption` is `144` (POP 4-103). I could not find the place where the facilities are mapped to these numbers, can you please point out where that is?

**Comment by JonPsson1** [comment]
> @JonPsson1 @uweigand I have a handful of questions about the contents of this PR that i would appreciate some feedback for..
> 
> 1. This PR assumes it is corrcect to use the same scheduling info for `TPEI` as for `TPI`. Is this correct`Where could i find information for potential dependencies of this instruction, and how would i map that to the template parameters available for`InstRW`?

This should be ok as they are both millicoded and not very relevant for optmizations as they are very slow. "Long latency millicoded" is the info we provide for these.

> 2. I picked `InherentDualRRE` as the instruction format, and set `hasSideEffects` to `0` based on the description in the POP. Is this correct?

As I read it, there is one input operand, and one output, so maybe 'Unary' would be a better match? It seems all the other millicoded instrucions have the side-effects flag set, so it should probably be the same here. This is not a type of instruction the optimizers should fiddle with, so that flag tells them to leave it alone and don't make assumptions about it and e.g. delete it.

**Comment by dominik-steenken** [comment]
> As I read it, there is one input operand, and one output, so maybe 'Unary' would be a better match?

`UnaryRRE` wants an `SDPatternOperator`, in addition to the register classes. Should i just pass in `null_frag` then?

> It seems all the other millicoded instrucions have the side-effects flag set, so it should probably be the same here. This is not a type of instruction the optimizers should fiddle with, so that flag tells them to leave it alone and don't make assumptions about it and e.g. delete it.

Ok, i'll set the sideeffects flag to `1` again.

**Comment by uweigand** [comment]
> `UnaryRRE` wants an `SDPatternOperator`, in addition to the register classes. Should i just pass in `null_frag` then?

Yes, it should be UnaryRRE with null_frag, and it should have side-effects (it looks at the interrupt status *here* and shouldn't be rescheduled across other instructions).

**Comment by JonPsson1** [comment]
Looking at MachineScheduler.cpp:isSchedBoundary() and TargetInstrInfo::isSchedulingBoundary(), it doesn't seem to me that the hasSideEffects flag implies a scheduling boundary, which to me is a bit unexpected. Maybe overload isSchedulingBoundary() and list opcodes there, like X86?

**Comment by dominik-steenken** [comment]
Ok, i used `UnaryRRE` and set the side effects flag again. What about the facility indicating bit vector from POP 4-103? Do i need to worry about that?

**Review by uweigand — APPROVED** [review]
LGTM now, thanks!

**Comment by uweigand** [comment]
> Looking at MachineScheduler.cpp:isSchedBoundary() and TargetInstrInfo::isSchedulingBoundary(), it doesn't seem to me that the hasSideEffects flag implies a scheduling boundary, which to me is a bit unexpected. Maybe overload isSchedulingBoundary() and list opcodes there, like X86?

Ah, it doesn't need to be an *absolute* scheduling boundary, it's fine to move it across instructions with no memory access or side effects - that would not be observable by other CPUs or I/O anyway.  It only needs to stay in the same position relative to other side effects (including memory accesses), which is what hasSideEffect does ensure.

**Comment by uweigand** [comment]
> Ok, i used `UnaryRRE` and set the side effects flag again. What about the facility indicating bit vector from POP 4-103? Do i need to worry about that?

No, the compiler doesn't look at that directly.  The compiler uses the command-line option (-march=) to decide which CPU is the *intended* target (which may not match the CPU where the compiler itself is running).

**Comment by uweigand** [comment]
> LGTM now, thanks!

Ah sorry, I missed one thing: normally, we verify that the feature test works correctly by adding a test that the instruction is *not* accepted when the feature is not present.  Could you add such a test for tpei to insn-bad-z13.s as well?  Thanks!

**Comment by dominik-steenken** [comment]
alright, i'll promote this PR to llvm then :)

**Comment by dominik-steenken** [comment]
> > LGTM now, thanks!
> 
> Ah sorry, I missed one thing: normally, we verify that the feature test works correctly by adding a test that the instruction is _not_ accepted when the feature is not present. Could you add such a test for tpei to insn-bad-z13.s as well? Thanks!

ok, will do

**Comment by dominik-steenken** [comment]
merged upstream

**Pull request closed without merging**
